spring:
  datasource:
    url: jdbc:sqlserver://demoappserver.database.windows.net:1433;database=demoapp;user=demoapp@demoappserver;password={Guru@123};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: demoapp
    password: Guru@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191

